"""
Analiz sonuçlarını JSON, CSV ve HTML formatlarında kaydeder.
"""

from __future__ import annotations

import csv
import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Image,
    KeepTogether,
    LongTable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.config import PROJECT_ROOT
from src.utils import ensure_directory


def _register_cyberlab_pdf_fonts() -> tuple[str, str]:
    """PDF için Türkçe karakterleri destekleyen font çiftini kaydeder."""

    candidates = [
        (
            Path(r"C:\Windows\Fonts\segoeui.ttf"),
            Path(r"C:\Windows\Fonts\segoeuib.ttf"),
            "CyberLabSegoe",
            "CyberLabSegoeBold",
        ),
        (
            Path(r"C:\Windows\Fonts\arial.ttf"),
            Path(r"C:\Windows\Fonts\arialbd.ttf"),
            "CyberLabArial",
            "CyberLabArialBold",
        ),
        (
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
            "CyberLabDejaVu",
            "CyberLabDejaVuBold",
        ),
    ]

    for regular_path, bold_path, regular_name, bold_name in candidates:
        if regular_path.exists() and bold_path.exists():
            if regular_name not in pdfmetrics.getRegisteredFontNames():
                pdfmetrics.registerFont(
                    TTFont(regular_name, str(regular_path))
                )
            if bold_name not in pdfmetrics.getRegisteredFontNames():
                pdfmetrics.registerFont(
                    TTFont(bold_name, str(bold_path))
                )
            return regular_name, bold_name

    return "Helvetica", "Helvetica-Bold"


def _pdf_paragraph(
    value: Any,
    style: ParagraphStyle,
) -> Paragraph:
    """Bir değeri güvenli bir ReportLab paragrafına dönüştürür."""

    text = html.escape(str(value if value is not None else "—"))
    return Paragraph(text, style)


def _cyberlab_pdf_page(
    canvas,
    doc,
    regular_font: str,
    bold_font: str,
) -> None:
    """Ortak PDF altbilgisini ve sayfa numarasını çizer."""

    canvas.saveState()
    width, _height = landscape(A4)
    canvas.setStrokeColor(colors.HexColor("#CBD5E1"))
    canvas.setLineWidth(0.5)
    canvas.line(
        doc.leftMargin,
        10 * mm,
        width - doc.rightMargin,
        10 * mm,
    )
    canvas.setFont(regular_font, 8)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.drawString(
        doc.leftMargin,
        6 * mm,
        "Generated by CyberLab Desktop Security Suite",
    )
    canvas.setFont(bold_font, 8)
    canvas.drawRightString(
        width - doc.rightMargin,
        6 * mm,
        f"Sayfa {doc.page}",
    )
    canvas.restoreState()


def save_json_report(
    report: dict[str, Any],
    output_file: Path,
) -> Path:
    """Tam analiz raporunu JSON formatında kaydeder."""

    ensure_directory(output_file.parent)

    with output_file.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            report,
            file,
            ensure_ascii=False,
            indent=2,
        )

    return output_file


def save_network_csv(
    report: dict[str, Any],
    output_file: Path,
) -> Path:
    """Tespit edilen ağları CSV formatında kaydeder."""

    ensure_directory(output_file.parent)

    with output_file.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as file:
        writer = csv.writer(file)

        writer.writerow(
            [
                "SSID",
                "BSSID",
                "Kanal",
                "Ortalama_Sinyal_dBm",
                "Istemci_Sayisi",
            ]
        )

        for network in report["networks"]:
            writer.writerow(
                [
                    " | ".join(network["ssids"]),
                    network["bssid"],
                    network["channel"],
                    network["average_signal_dbm"],
                    len(network["clients"]),
                ]
            )

    return output_file


def save_clients_csv(
    report: dict[str, Any],
    output_file: Path,
) -> Path:
    """Ağ ve istemci ilişkilerini CSV formatında kaydeder."""

    ensure_directory(output_file.parent)

    with output_file.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as file:
        writer = csv.writer(file)

        writer.writerow(
            [
                "BSSID",
                "SSID",
                "Istemci_MAC",
                "Paket_Sayisi",
            ]
        )

        for network in report["networks"]:
            ssid_text = " | ".join(network["ssids"])

            for client in network["clients"]:
                writer.writerow(
                    [
                        network["bssid"],
                        ssid_text,
                        client["mac"],
                        client["packet_count"],
                    ]
                )

    return output_file


def save_html_report(
    report: dict[str, Any],
    output_file: Path,
    capture_name: str,
) -> Path:
    """Okunabilir ve markalı bir HTML analiz raporu oluşturur."""

    ensure_directory(output_file.parent)

    network_rows: list[str] = []

    for network in report.get("networks", []):
        ssid_text = (
            ", ".join(network.get("ssids", []))
            if network.get("ssids")
            else "SSID belirlenemedi"
        )

        channel = (
            network.get("channel")
            if network.get("channel") is not None
            else "Bilinmiyor"
        )

        signal_value = network.get("average_signal_dbm")
        signal = (
            f"{signal_value} dBm"
            if signal_value is not None
            else "Bilinmiyor"
        )

        client_rows: list[str] = []

        for client in network.get("clients", [])[:25]:
            client_rows.append(
                "<tr>"
                f"<td>{html.escape(str(client.get('mac', '—')))}</td>"
                f"<td>{html.escape(str(client.get('vendor', 'Bilinmiyor')))}</td>"
                f"<td>{html.escape(str(client.get('packet_count', 0)))}</td>"
                f"<td>{html.escape(str(client.get('sent_packets', 0)))}</td>"
                f"<td>{html.escape(str(client.get('received_packets', 0)))}</td>"
                f"<td>{html.escape(str(client.get('first_seen', '—')))}</td>"
                f"<td>{html.escape(str(client.get('last_seen', '—')))}</td>"
                f"<td>{html.escape(str(client.get('activity_level', '—')))}</td>"
                "</tr>"
            )

        clients_table = (
            "<table>"
            "<thead><tr>"
            "<th>İstemci MAC</th>"
            "<th>Vendor</th>"
            "<th>Toplam Paket</th>"
            "<th>Gönderilen</th>"
            "<th>Alınan</th>"
            "<th>İlk Görülme</th>"
            "<th>Son Görülme</th>"
            "<th>Aktivite</th>"
            "</tr></thead>"
            "<tbody>"
            + (
                "".join(client_rows)
                if client_rows
                else (
                    "<tr><td colspan='8'>"
                    "Bu ağ için istemci gözlemlenmedi."
                    "</td></tr>"
                )
            )
            + "</tbody>"
            "</table>"
        )

        network_rows.append(
            "<section class='network-card'>"
            f"<h3>{html.escape(ssid_text)}</h3>"
            "<dl>"
            f"<dt>BSSID</dt><dd>{html.escape(str(network.get('bssid', '—')))}</dd>"
            f"<dt>Kanal</dt><dd>{html.escape(str(channel))}</dd>"
            f"<dt>Ortalama sinyal</dt><dd>{html.escape(signal)}</dd>"
            f"<dt>İstemci sayısı</dt><dd>{len(network.get('clients', []))}</dd>"
            "</dl>"
            f"{clients_table}"
            "</section>"
        )

    subtype_rows: list[str] = []

    for subtype, count in report.get("frame_subtypes", {}).items():
        subtype_rows.append(
            "<tr>"
            f"<td>{html.escape(str(subtype))}</td>"
            f"<td>{html.escape(str(count))}</td>"
            "</tr>"
        )

    generated_at = datetime.now().strftime("%d.%m.%Y %H:%M:%S")

    findings = report.get("security_findings", [])
    finding_rows: list[str] = []

    severity_map = {
        "critical": ("KRİTİK", "#ef4444"),
        "warning": ("UYARI", "#f59e0b"),
        "success": ("BAŞARILI", "#10b981"),
        "info": ("BİLGİ", "#3b82f6"),
    }

    for finding in findings:
        severity = str(finding.get("severity", "info"))

        label, color = severity_map.get(
            severity,
            ("BİLGİ", "#3b82f6"),
        )

        title = html.escape(
            str(finding.get("title", "Bulgu"))
        )

        description = html.escape(
            str(finding.get("description", ""))
        )

        finding_rows.append(
            f"""
            <div class="finding">
                <div
                    class="finding-indicator"
                    style="background:{color};"
                ></div>

                <div class="finding-content">
                    <div class="finding-header">
                        <span
                            class="finding-badge"
                            style="
                                color:{color};
                                border-color:{color};
                            "
                        >
                            {label}
                        </span>

                        <strong>{title}</strong>
                    </div>

                    <p>{description}</p>
                </div>
            </div>
            """
        )

    findings_html = (
        "".join(finding_rows)
        if finding_rows
        else """
        <div class="finding">
            <div
                class="finding-indicator"
                style="background:#10b981;"
            ></div>

            <div class="finding-content">
                <div class="finding-header">
                    <span
                        class="finding-badge"
                        style="
                            color:#10b981;
                            border-color:#10b981;
                        "
                    >
                        BİLGİ
                    </span>

                    <strong>
                        Ek güvenlik bulgusu bulunamadı
                    </strong>
                </div>

                <p>
                    Analiz motoru bu yakalama için
                    ek bir güvenlik bulgusu üretmedi.
                </p>
            </div>
        </div>
        """
    )

    document = f"""<!doctype html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
    >
    <title>CyberLab Wi-Fi Forensics Report</title>

    <style>
        * {{
            box-sizing: border-box;
        }}

        body {{
            margin: 0;
            padding: 0;
            background: #f1f5f9;
            color: #1e293b;
            font-family: "Segoe UI", Arial, sans-serif;
        }}

        main {{
            max-width: 1100px;
            margin: 0 auto;
            padding: 36px 24px 60px;
        }}

        .report-header {{
            background: #0f172a;
            color: #ffffff;
            padding: 32px;
            border: 1px solid #1e293b;
            border-radius: 14px;
            margin-bottom: 24px;
        }}

        .brand {{
            color: #2dd4bf;
            font-size: 15px;
            font-weight: 800;
            letter-spacing: 4px;
            margin-bottom: 8px;
        }}

        .report-header h1 {{
            margin: 0 0 8px;
            font-size: 30px;
            font-weight: 800;
        }}

        .report-header > p {{
            margin: 0;
            color: #cbd5e1;
            font-size: 14px;
        }}

        .metadata {{
            display: grid;
            grid-template-columns:
                repeat(auto-fit, minmax(220px, 1fr));
            gap: 12px;
            margin-top: 24px;
        }}

        .metadata-item {{
            border: 1px solid #334155;
            border-radius: 8px;
            padding: 10px 12px;
            color: #f8fafc;
        }}

        .metadata-label {{
            display: block;
            color: #94a3b8;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            margin-bottom: 4px;
        }}

        .summary {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 16px;
            margin-bottom: 30px;
        }}

        .summary-card {{
            background: #ffffff;
            border: 1px solid #dbe3ec;
            border-radius: 12px;
            padding: 18px;
        }}

        .summary-label {{
            color: #64748b;
            font-size: 13px;
            font-weight: 600;
        }}

        .summary-value {{
            display: block;
            color: #0f172a;
            font-size: 28px;
            font-weight: 800;
            margin-top: 8px;
        }}

        .report-section {{
            margin-top: 30px;
        }}

        .section-title {{
            color: #0f172a;
            font-size: 19px;
            font-weight: 800;
            margin: 0 0 14px;
            padding-bottom: 8px;
            border-bottom: 2px solid #2dd4bf;
        }}

        .finding {{
            display: grid;
            grid-template-columns: 5px 1fr;
            gap: 14px;
            background: #ffffff;
            border: 1px solid #dbe3ec;
            border-radius: 10px;
            padding: 14px;
            margin-bottom: 10px;
        }}

        .finding-indicator {{
            border-radius: 5px;
        }}

        .finding-content {{
            min-width: 0;
        }}

        .finding-header {{
            display: flex;
            align-items: center;
            gap: 10px;
        }}

        .finding-header strong {{
            color: #0f172a;
        }}

        .finding-badge {{
            display: inline-block;
            border: 1px solid;
            border-radius: 5px;
            padding: 2px 6px;
            font-size: 10px;
            font-weight: 800;
        }}

        .finding p {{
            margin: 6px 0 0;
            color: #64748b;
            font-size: 13px;
            line-height: 1.5;
        }}

        .network-card {{
            background: #ffffff;
            border: 1px solid #dbe3ec;
            border-radius: 10px;
            padding: 18px;
            margin-bottom: 16px;
        }}

        .network-card h3 {{
            color: #0f172a;
            margin: 0 0 14px;
            font-size: 17px;
        }}

        dl {{
            display: grid;
            grid-template-columns: 180px 1fr;
            gap: 8px 16px;
            margin: 0;
        }}

        dt {{
            color: #64748b;
            font-weight: 600;
        }}

        dd {{
            margin: 0;
            color: #0f172a;
            font-weight: 600;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 14px;
            background: #ffffff;
        }}

        th {{
            background: #f8fafc;
            color: #475569;
            font-size: 12px;
            font-weight: 700;
            text-transform: uppercase;
        }}

        th,
        td {{
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
            padding: 9px 10px;
        }}

        td {{
            color: #334155;
        }}

        .empty-state {{
            background: #ffffff;
            border: 1px solid #dbe3ec;
            border-radius: 10px;
            padding: 16px;
            color: #64748b;
        }}

        .disclaimer {{
            margin-top: 36px;
            padding: 16px;
            background: #f8fafc;
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            color: #64748b;
            font-size: 12px;
            line-height: 1.6;
        }}

        .disclaimer strong {{
            color: #334155;
        }}

        footer {{
            margin-top: 28px;
            text-align: center;
            color: #94a3b8;
            font-size: 11px;
        }}

        @media (max-width: 700px) {{
            .summary {{
                grid-template-columns: 1fr;
            }}

            .metadata {{
                grid-template-columns: 1fr;
            }}

            dl {{
                grid-template-columns: 1fr;
            }}

            main {{
                padding: 18px 12px 40px;
            }}

            .report-header {{
                padding: 22px;
            }}

            .report-header h1 {{
                font-size: 24px;
            }}
        }}
    </style>
</head>

<body>
<main>

    <header class="report-header">
        <div class="brand">
            CYBERLAB
        </div>

        <h1>
            Wi-Fi Forensics Analysis Report
        </h1>

        <p>
            Kablosuz ağ yakalama dosyası analiz raporu
        </p>

        <div class="metadata">
            <div class="metadata-item">
                <span class="metadata-label">
                    Yakalama Dosyası
                </span>
                {html.escape(capture_name)}
            </div>

            <div class="metadata-item">
                <span class="metadata-label">
                    Rapor Tarihi
                </span>
                {generated_at}
            </div>

            <div class="metadata-item">
                <span class="metadata-label">
                    Analiz Modülü
                </span>
                Wi-Fi Forensics
            </div>
        </div>
    </header>

    <div class="summary">
        <div class="summary-card">
            <span class="summary-label">
                Toplam Paket
            </span>
            <strong class="summary-value">
                {report.get("total_packets", 0)}
            </strong>
        </div>

        <div class="summary-card">
            <span class="summary-label">
                Tespit Edilen Ağ
            </span>
            <strong class="summary-value">
                {report.get("network_count", 0)}
            </strong>
        </div>

        <div class="summary-card">
            <span class="summary-label">
                EAPOL Paketleri
            </span>
            <strong class="summary-value">
                {report.get("eapol_packet_count", 0)}
            </strong>
        </div>
    </div>

    <section class="report-section">
        <h2 class="section-title">
            Security Findings
        </h2>
        {findings_html}
    </section>

    <section class="report-section">
        <h2 class="section-title">
            Tespit Edilen Ağlar
        </h2>

        {
            "".join(network_rows)
            if network_rows
            else (
                '<div class="empty-state">'
                'Analiz sonucunda kablosuz ağ '
                'tespit edilmedi.'
                '</div>'
            )
        }
    </section>

    <section class="report-section">
        <h2 class="section-title">
            802.11 Frame Analysis
        </h2>

        <table>
            <thead>
                <tr>
                    <th>Frame Alt Tipi</th>
                    <th>Paket Sayısı</th>
                </tr>
            </thead>

            <tbody>
                {
                    "".join(subtype_rows)
                    if subtype_rows
                    else (
                        "<tr>"
                        "<td colspan='2'>"
                        "Frame alt tipi verisi bulunamadı."
                        "</td>"
                        "</tr>"
                    )
                }
            </tbody>
        </table>
    </section>

    <div class="disclaimer">
        <strong>
            Analiz Notu:
        </strong>

        Bu rapor, yakalama dosyasında gözlemlenen
        veriler üzerinden otomatik olarak oluşturulmuştur.
        Bir bulgunun raporda bulunmaması,
        ilgili güvenlik olayının gerçekleşmediğini
        tek başına kanıtlamaz.
    </div>

    <footer>
        Generated by CyberLab Desktop Security Suite
    </footer>

</main>
</body>
</html>
"""

    with output_file.open(
        "w",
        encoding="utf-8",
    ) as file:
        file.write(document)

    return output_file


def generate_all_reports(
    report: dict[str, Any],
    reports_dir: Path,
    base_name: str,
    capture_name: str,
) -> list[Path]:
    """Tüm rapor formatlarını tek seferde üretir."""

    ensure_directory(reports_dir)

    created_files = [
        save_json_report(
            report,
            reports_dir / f"{base_name}.json",
        ),
        save_network_csv(
            report,
            reports_dir / f"{base_name}_networks.csv",
        ),
        save_clients_csv(
            report,
            reports_dir / f"{base_name}_clients.csv",
        ),
        save_html_report(
            report,
            reports_dir / f"{base_name}.html",
            capture_name,
        ),
    ]

    return created_files

def export_json_report(
    report: dict,
    output_dir: Path,
) -> Path:
    """CyberLab analiz sonucunu JSON raporu olarak kaydeder."""

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    output_path = (
        output_dir
        / f"cyberlab_report_{timestamp}.json"
    )

    payload = {
        "product": "CyberLab",
        "module": "Wi-Fi Forensics",
        "generated_at": datetime.now().isoformat(
            timespec="seconds"
        ),
        "report": report,
    }

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            payload,
            file,
            indent=4,
            ensure_ascii=False,
            default=str,
        )

    return output_path


def save_anomaly_json_report(
    session: dict[str, Any],
    output_file: Path,
) -> Path:
    """Canlı anomaly session verisini JSON olarak kaydeder."""

    ensure_directory(output_file.parent)
    with output_file.open("w", encoding="utf-8") as file:
        json.dump(
            session,
            file,
            ensure_ascii=False,
            indent=2,
        )
    return output_file


def save_anomaly_pdf_report(
    session: dict[str, Any],
    output_file: Path,
) -> Path:
    """Canlı anomaly session verisini ReportLab PDF olarak kaydeder."""

    ensure_directory(output_file.parent)
    regular_font, bold_font = _register_cyberlab_pdf_fonts()
    styles = getSampleStyleSheet()
    body_style = ParagraphStyle(
        "AnomalyBody",
        parent=styles["BodyText"],
        fontName=regular_font,
        fontSize=9,
        leading=11,
    )
    heading_style = ParagraphStyle(
        "AnomalyHeading",
        parent=styles["Heading1"],
        fontName=bold_font,
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#0F172A"),
    )
    title_style = ParagraphStyle(
        "CyberLabAnomalyTitle",
        parent=styles["Title"],
        fontName=bold_font,
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=2 * mm,
    )
    subtitle_style = ParagraphStyle(
        "CyberLabAnomalySubtitle",
        parent=styles["BodyText"],
        fontName=regular_font,
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=5 * mm,
    )

    doc = SimpleDocTemplate(
        str(output_file),
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=16 * mm,
        title="CyberLab Anomaly Session Report",
        author="CyberLab Desktop Security Suite",
    )
    story: list[Any] = []
    logo_path = (
        PROJECT_ROOT
        / "resources"
        / "logo"
        / "cyberlab_logo.png"
    )
    if logo_path.exists():
        logo = Image(
            str(logo_path),
            width=34 * mm,
            height=18 * mm,
        )
        logo.hAlign = "LEFT"
        story.append(logo)
        story.append(Spacer(1, 3 * mm))

    story.extend(
        [
            Paragraph(
                "CyberLab Anomaly Monitoring Report",
                title_style,
            ),
            Paragraph(
                "Live Network Traffic & Anomaly Detection Session",
                subtitle_style,
            ),
        ]
    )
    story.extend(
        [
        _pdf_paragraph(
            f"Interface: {session.get('interface', '—')}",
            body_style,
        ),
        Spacer(1, 5 * mm),
        ]
    )

    summary = session.get("summary") or {
        "duration": session.get("duration_text", "00:00"),
        "total_packets": session.get("total_packets", 0),
        "total_data": session.get("total_data_text", "0 MB"),
        "peak": session.get("peak_text", "0.00 Mbps"),
        "point": session.get("point_count", 0),
        "contextual": session.get("contextual_count", 0),
        "collective": session.get("collective_count", 0),
        "total_anomalies": session.get("total_findings", 0),
    }
    summary_cards = [
        ["Interface", session.get("interface", "—")],
        ["Duration", summary.get("duration", "00:00")],
        [
            "Total Packets",
            f"{int(summary.get('total_packets', 0)):,}",
        ],
        ["Total Data", summary.get("total_data", "0 MB")],
        ["Peak", summary.get("peak", "0.00 Mbps")],
        [
            "Total Findings",
            str(summary.get("total_anomalies", 0)),
        ],
    ]
    summary_table = Table(
        summary_cards,
        colWidths=[45 * mm, 120 * mm],
        hAlign="LEFT",
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#E2E8F0")),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F8FAFC")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(summary_table)
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph("Anomaly Findings", styles["Heading2"]))

    findings = session.get("findings", [])
    if not findings:
        story.append(
            Paragraph(
                "No anomaly findings were produced.",
                body_style,
            )
        )
    else:
        finding_rows = [
            [
                "Type",
                "Severity",
                "Time",
                "Observed",
                "Baseline / Context",
            ]
        ]
        for finding in findings:
            finding_rows.append(
                [
                    str(finding.get("type", "—")).upper(),
                    str(finding.get("severity", "—")).upper(),
                    str(finding.get("elapsed_seconds", 0)),
                    f"{float(finding.get('value_mbps', 0)):.2f} Mbps",
                    str(
                        finding.get(
                            "baseline_mbps",
                            finding.get("long_mean_mbps", "—"),
                        )
                    ),
                ]
            )
        findings_table = Table(
            finding_rows,
            repeatRows=1,
            colWidths=[30 * mm, 30 * mm, 22 * mm, 38 * mm, 45 * mm],
            hAlign="LEFT",
        )
        findings_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]
        for row_index, finding in enumerate(findings, start=1):
            severity = str(finding.get("severity", "info")).lower()
            if severity == "critical":
                background = colors.HexColor("#FEE2E2")
                foreground = colors.HexColor("#B91C1C")
            elif severity == "warning":
                background = colors.HexColor("#FEF3C7")
                foreground = colors.HexColor("#B45309")
            else:
                background = colors.HexColor("#DBEAFE")
                foreground = colors.HexColor("#1D4ED8")
            findings_style.extend(
                [
                    ("BACKGROUND", (1, row_index), (1, row_index), background),
                    ("TEXTCOLOR", (1, row_index), (1, row_index), foreground),
                ]
            )
        findings_table.setStyle(
            TableStyle(findings_style)
        )
        story.append(findings_table)

    story.append(Spacer(1, 6 * mm))
    note = Paragraph(
        "<b>Analiz Notu:</b> Bu rapor, izleme oturumu sırasında "
        "gözlemlenen trafik davranışlarından otomatik olarak "
        "üretilmiştir. Bir anomali, tek başına saldırı veya "
        "güvenlik ihlali kanıtı değildir.",
        body_style,
    )
    note_table = Table(
        [[note]],
        colWidths=[165 * mm],
        hAlign="LEFT",
    )
    note_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#CBD5E1")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(note_table)

    doc.build(story)
    return output_file


def save_pdf_report(
    report: dict[str, Any],
    output_file: Path,
    capture_name: str,
) -> Path:
    """Kararlı sayfalamayla A4 yatay ReportLab PDF raporu oluşturur."""

    ensure_directory(output_file.parent)
    regular_font, bold_font = _register_cyberlab_pdf_fonts()

    doc = SimpleDocTemplate(
        str(output_file),
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=16 * mm,
        title="CyberLab Wi-Fi Forensics Analysis Report",
        author="CyberLab Desktop Security Suite",
        subject="Wi-Fi Forensics Analysis Report",
    )

    sample_styles = getSampleStyleSheet()
    body_style = ParagraphStyle(
        "CyberLabBody",
        parent=sample_styles["BodyText"],
        fontName=regular_font,
        fontSize=8.6,
        leading=11,
        textColor=colors.HexColor("#334155"),
        spaceAfter=2,
    )
    small_style = ParagraphStyle(
        "CyberLabSmall",
        parent=body_style,
        fontSize=7.4,
        leading=9,
    )
    heading_style = ParagraphStyle(
        "CyberLabHeading",
        parent=sample_styles["Heading1"],
        fontName=bold_font,
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=5 * mm,
    )
    section_style = ParagraphStyle(
        "CyberLabSection",
        parent=sample_styles["Heading2"],
        fontName=bold_font,
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=5 * mm,
        spaceAfter=3 * mm,
    )
    network_title_style = ParagraphStyle(
        "CyberLabNetworkTitle",
        parent=sample_styles["Heading3"],
        fontName=bold_font,
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=1 * mm,
        spaceAfter=2 * mm,
    )
    label_style = ParagraphStyle(
        "CyberLabLabel",
        parent=body_style,
        fontName=bold_font,
        fontSize=7.6,
        leading=9,
        textColor=colors.HexColor("#64748B"),
    )
    table_header_style = ParagraphStyle(
        "CyberLabTableHeader",
        parent=small_style,
        fontName=bold_font,
        fontSize=6.7,
        leading=8,
        textColor=colors.HexColor("#334155"),
        alignment=TA_LEFT,
    )
    table_cell_style = ParagraphStyle(
        "CyberLabTableCell",
        parent=small_style,
        fontName=regular_font,
        fontSize=6.8,
        leading=8.2,
        textColor=colors.HexColor("#334155"),
    )
    finding_title_style = ParagraphStyle(
        "CyberLabFindingTitle",
        parent=body_style,
        fontName=bold_font,
        fontSize=8.6,
        leading=10.5,
        textColor=colors.HexColor("#0F172A"),
    )
    finding_description_style = ParagraphStyle(
        "CyberLabFindingDescription",
        parent=body_style,
        fontSize=7.8,
        leading=10,
        textColor=colors.HexColor("#475569"),
    )
    summary_value_style = ParagraphStyle(
        "CyberLabSummaryValue",
        parent=body_style,
        fontName=bold_font,
        fontSize=15,
        leading=18,
        textColor=colors.HexColor("#0F172A"),
    )

    story: list[Any] = []
    logo_path = PROJECT_ROOT / "resources" / "logo" / "cyberlab_logo.png"
    header_left: list[Any] = []
    if logo_path.exists():
        logo = Image(str(logo_path), width=34 * mm, height=18 * mm)
        logo.hAlign = "LEFT"
        header_left.append(logo)
    header_left.extend(
        [
            Paragraph("Wi-Fi Forensics Analysis Report", heading_style),
            Paragraph(
                "Kablosuz ağ yakalama dosyası analiz raporu",
                body_style,
            ),
        ]
    )

    metadata_table = Table(
        [
            [
                Paragraph("YAKALAMA DOSYASI", label_style),
                _pdf_paragraph(capture_name, body_style),
            ],
            [
                Paragraph("RAPOR TARİHİ", label_style),
                _pdf_paragraph(
                    datetime.now().strftime("%d.%m.%Y %H:%M:%S"),
                    body_style,
                ),
            ],
            [
                Paragraph("ANALİZ MODÜLÜ", label_style),
                Paragraph("Wi-Fi Forensics", body_style),
            ],
        ],
        colWidths=[34 * mm, 80 * mm],
        hAlign="RIGHT",
    )
    metadata_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 3),
                ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                (
                    "LINEBELOW",
                    (0, 0),
                    (-1, -1),
                    0.3,
                    colors.HexColor("#E2E8F0"),
                ),
            ]
        )
    )
    header_table = Table(
        [[header_left, metadata_table]],
        colWidths=[126 * mm, 114 * mm],
        hAlign="LEFT",
    )
    header_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#14B8A6")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend([header_table, Spacer(1, 5 * mm)])

    summary_items = [
        ("Toplam Paket", f"{int(report.get('total_packets', 0)):,}"),
        (
            "Tespit Edilen Ağ",
            str(report.get("network_count", len(report.get("networks", [])))),
        ),
        ("EAPOL Paketleri", str(report.get("eapol_packet_count", 0))),
    ]
    summary_table = Table(
        [
            [
                [
                    Paragraph(title, label_style),
                    Paragraph(value, summary_value_style),
                ]
                for title, value in summary_items
            ]
        ],
        colWidths=[80 * mm, 80 * mm, 80 * mm],
        hAlign="LEFT",
    )
    summary_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#CBD5E1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.extend([summary_table, Spacer(1, 4 * mm)])

    story.append(Paragraph("Security Findings", section_style))
    severity_colors = {
        "critical": colors.HexColor("#DC2626"),
        "warning": colors.HexColor("#D97706"),
        "success": colors.HexColor("#059669"),
        "info": colors.HexColor("#2563EB"),
    }
    severity_labels = {
        "critical": "KRİTİK",
        "warning": "UYARI",
        "success": "BAŞARILI",
        "info": "BİLGİ",
    }
    findings = report.get("security_findings", [])
    if findings:
        for finding in findings:
            severity = str(finding.get("severity", "info")).lower()
            color = severity_colors.get(severity, colors.HexColor("#64748B"))
            badge_style = ParagraphStyle(
                f"CyberLabFindingBadge{severity}",
                parent=small_style,
                fontName=bold_font,
                fontSize=7,
                leading=8,
                textColor=color,
            )
            finding_table = Table(
                [
                    [
                        Paragraph(
                            severity_labels.get(severity, "BİLGİ"),
                            badge_style,
                        ),
                        _pdf_paragraph(
                            str(finding.get("category", "general")).upper(),
                            small_style,
                        ),
                        _pdf_paragraph(
                            finding.get("title", "Bulgu"),
                            finding_title_style,
                        ),
                    ],
                    [
                        "",
                        "",
                        _pdf_paragraph(
                            finding.get("description", ""),
                            finding_description_style,
                        ),
                    ],
                ],
                colWidths=[22 * mm, 30 * mm, 188 * mm],
                hAlign="LEFT",
            )
            finding_table.setStyle(
                TableStyle(
                    [
                        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                        ("LINEBEFORE", (0, 0), (0, -1), 3, color),
                        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                        ("SPAN", (0, 1), (1, 1)),
                    ]
                )
            )
            story.extend([finding_table, Spacer(1, 2 * mm)])
    else:
        story.append(
            Paragraph(
                "Analiz sonucunda ek bir güvenlik bulgusu üretilmedi.",
                body_style,
            )
        )

    story.append(Paragraph("Tespit Edilen Ağlar", section_style))
    networks = report.get("networks", [])
    if not networks:
        story.append(
            Paragraph(
                "Analiz sonucunda kablosuz ağ tespit edilmedi.",
                body_style,
            )
        )

    client_header = [
        Paragraph("İSTEMCİ MAC", table_header_style),
        Paragraph("VENDOR", table_header_style),
        Paragraph("TOPLAM", table_header_style),
        Paragraph("GÖNDERİLEN", table_header_style),
        Paragraph("ALINAN", table_header_style),
        Paragraph("İLK GÖRÜLME", table_header_style),
        Paragraph("SON GÖRÜLME", table_header_style),
        Paragraph("AKTİVİTE", table_header_style),
    ]
    client_col_widths = [
        39 * mm,
        50 * mm,
        22 * mm,
        24 * mm,
        20 * mm,
        29 * mm,
        29 * mm,
        25 * mm,
    ]

    for network_index, network in enumerate(networks):
        ssids = network.get("ssids", [])
        ssid_text = (
            ", ".join(str(value) for value in ssids)
            if ssids
            else "SSID belirlenemedi"
        )
        channel = network.get("channel", "Bilinmiyor")
        if channel is None:
            channel = "Bilinmiyor"
        signal_value = network.get("average_signal_dbm")
        signal_text = (
            f"{signal_value} dBm"
            if signal_value is not None
            else "Bilinmiyor"
        )
        clients = list(network.get("clients", []))
        network_table = Table(
            [
                [
                    Paragraph("BSSID", label_style),
                    _pdf_paragraph(network.get("bssid", "—"), body_style),
                    Paragraph("Kanal", label_style),
                    _pdf_paragraph(channel, body_style),
                    Paragraph("Ortalama sinyal", label_style),
                    _pdf_paragraph(signal_text, body_style),
                    Paragraph("İstemci sayısı", label_style),
                    _pdf_paragraph(len(clients), body_style),
                ]
            ],
            colWidths=[
                18 * mm,
                48 * mm,
                16 * mm,
                24 * mm,
                30 * mm,
                32 * mm,
                24 * mm,
                24 * mm,
            ],
            hAlign="LEFT",
        )
        network_table.setStyle(
            TableStyle(
                [
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )
        story.append(
            KeepTogether(
                [
                    _pdf_paragraph(ssid_text, network_title_style),
                    network_table,
                    Spacer(1, 2 * mm),
                ]
            )
        )

        displayed_clients = clients[:25]
        client_rows = [client_header]
        for client in displayed_clients:
            client_rows.append(
                [
                    _pdf_paragraph(client.get("mac", "—"), table_cell_style),
                    _pdf_paragraph(client.get("vendor", "Bilinmiyor"), table_cell_style),
                    _pdf_paragraph(client.get("packet_count", 0), table_cell_style),
                    _pdf_paragraph(client.get("sent_packets", 0), table_cell_style),
                    _pdf_paragraph(client.get("received_packets", 0), table_cell_style),
                    _pdf_paragraph(client.get("first_seen", "—"), table_cell_style),
                    _pdf_paragraph(client.get("last_seen", "—"), table_cell_style),
                    _pdf_paragraph(client.get("activity_level", "—"), table_cell_style),
                ]
            )

        if displayed_clients:
            clients_table = LongTable(
                client_rows,
                colWidths=client_col_widths,
                repeatRows=1,
                hAlign="LEFT",
            )
            clients_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#334155")),
                        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
                        (
                            "ROWBACKGROUNDS",
                            (0, 1),
                            (-1, -1),
                            [colors.white, colors.HexColor("#F8FAFC")],
                        ),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 3),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            story.append(clients_table)
            if len(clients) > 25:
                story.extend(
                    [
                        Spacer(1, 1.5 * mm),
                        Paragraph(
                            (
                                f"Not: Bu ağda toplam {len(clients)} istemci "
                                "gözlemlendi; raporda paket aktivitesine göre "
                                "ilk 25 istemci gösteriliyor."
                            ),
                            small_style,
                        ),
                    ]
                )
        else:
            story.append(
                Paragraph("Bu ağ için istemci gözlemlenmedi.", body_style)
            )
        if network_index != len(networks) - 1:
            story.append(Spacer(1, 5 * mm))

    story.extend(
        [
            PageBreak(),
            Paragraph("802.11 Frame Analysis", section_style),
        ]
    )
    frame_rows = [
        [
            Paragraph("FRAME ALT TİPİ", table_header_style),
            Paragraph("PAKET SAYISI", table_header_style),
        ]
    ]
    for subtype, count in sorted(
        report.get("frame_subtypes", {}).items(),
        key=lambda item: int(item[1]),
        reverse=True,
    ):
        frame_rows.append(
            [
                _pdf_paragraph(subtype, table_cell_style),
                _pdf_paragraph(count, table_cell_style),
            ]
        )
    if len(frame_rows) == 1:
        frame_rows.append(
            [
                Paragraph("Frame alt tipi verisi bulunamadı.", table_cell_style),
                Paragraph("—", table_cell_style),
            ]
        )
    frame_table = LongTable(
        frame_rows,
        colWidths=[165 * mm, 45 * mm],
        repeatRows=1,
        hAlign="LEFT",
    )
    frame_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#F8FAFC")],
                ),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    story.extend([frame_table, Spacer(1, 6 * mm)])

    disclaimer_table = Table(
        [
            [
                Paragraph(
                    (
                        "<b>Analiz Notu:</b> Bu rapor, yakalama dosyasında "
                        "gözlemlenen veriler üzerinden otomatik olarak "
                        "oluşturulmuştur. Bir bulgunun raporda bulunmaması, "
                        "ilgili güvenlik olayının gerçekleşmediğini tek "
                        "başına kanıtlamaz."
                    ),
                    small_style,
                )
            ]
        ],
        colWidths=[240 * mm],
        hAlign="LEFT",
    )
    disclaimer_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#CBD5E1")),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(disclaimer_table)

    def page_callback(canvas, document) -> None:
        _cyberlab_pdf_page(
            canvas,
            document,
            regular_font,
            bold_font,
        )

    doc.build(
        story,
        onFirstPage=page_callback,
        onLaterPages=page_callback,
    )
    return output_file
